/**
 * Source Asset ID parser — shared utility.
 *
 * Parses a 14-15 position Asset ID string into an AssetIdPositions object.
 * This is the INVERSE of naming_generator's assembleFullId.
 *
 * Handles two format versions:
 * - v3.3+ (15 positions): includes CountryCode at Position 13
 * - v3.2  (14 positions): no CountryCode, CreationDate at Position 13
 *
 * Detection heuristic (from Tess's naming_parser.py):
 *   Position index 12 is examined:
 *   - If it's a 2-letter alpha string in VALID_COUNTRY_CODES → v3.3
 *   - If it's an 8-digit date string → v3.2 (no country code)
 */

import type { AssetIdPositions } from "../types/pipeline.js";
import {
  VALID_PLATFORMS,
  VALID_LENGTH_TIERS,
  VALID_AD_CATEGORIES,
  VALID_EXPANSION_TYPES,
  VALID_ASSET_TYPES,
  VALID_COUNTRY_CODES,
  SCRIPT_ID_PATTERN,
  VARIATION_ID_PATTERN,
  DIMENSIONS_PATTERN,
  CREATION_DATE_PATTERN,
} from "../tables/naming-codes.js";

// Legacy ad categories accepted by parser (not generated by Veda)
const PARSER_AD_CATEGORIES = new Set([
  ...VALID_AD_CATEGORIES,
  "ver",  // legacy vertical
  "hor",  // legacy horizontal
]);

// Old-format length tier → v3.4 mapping
const OLD_LENGTH_TIER_MAP: Record<string, string> = {
  "0min": "30s",
  "1min": "60s",
  "2min": "180s",
  "3min": "180s",
  "5min": "360s+",
};

// Old-format asset types accepted by parser but not in v3.4 generation tables
const PARSER_ASSET_TYPES = new Set([
  ...VALID_ASSET_TYPES,
  "vd",   // legacy generic video
]);

export interface ParseResult {
  status: "PARSED" | "ERROR";
  positions?: AssetIdPositions;
  format_version?: "v3.3" | "v3.2";
  warnings: string[];
  errors: string[];
}

/**
 * Parse a source asset ID string into its named positions.
 *
 * Accepts both v3.2 (14 positions, no country code) and v3.3+ (15 positions).
 * Promo name (optional) adds one additional position in either version.
 *
 * @param assetId - The full asset ID string (hyphen-separated)
 * @returns ParseResult with positions or errors
 */
export function parseAssetId(assetId: string): ParseResult {
  const warnings: string[] = [];
  const errors: string[] = [];

  if (!assetId || assetId.trim().length === 0) {
    return { status: "ERROR", warnings, errors: ["Asset ID is empty"] };
  }

  // Strip SSS artifacts before parsing (order matters: Sheets suffix first, then extension)
  let workingId = assetId.trim().toLowerCase();

  // Strip Google Sheets copy/variant suffixes: " - copy 3", " - ac", " - anything"
  // Space-dash-space never appears in legitimate asset ID positions
  const beforeSheetStrip = workingId;
  workingId = workingId.replace(/\s+-\s+.*$/, "");
  if (workingId !== beforeSheetStrip) {
    warnings.push("Stripped Google Sheets suffix");
  }

  // Strip file extension (.mp4, .mov, etc.)
  const beforeExtStrip = workingId;
  workingId = workingId.replace(/\.(mp4|mov|avi|mkv)$/, "");
  if (workingId !== beforeExtStrip) {
    warnings.push("Stripped file extension");
  }

  // Strip trailing -sca (scaling variant suffix)
  if (workingId.endsWith("-sca")) {
    workingId = workingId.slice(0, -4);
    warnings.push("Stripped -sca scaling variant suffix");
  }

  const parts = workingId.split("-");

  // Minimum 13 positions (v3.2 without promo) to maximum 16 (v3.3 with promo)
  // Old-format IDs (< 13 positions) get best-effort heuristic parsing
  if (parts.length < 13) {
    if (parts.length < 3) {
      return {
        status: "ERROR",
        warnings,
        errors: [`Asset ID has only ${parts.length} positions — need at least funnel-scriptId-variation`],
      };
    }
    return parseOldFormat(parts, warnings);
  }
  if (parts.length > 16) {
    return {
      status: "ERROR",
      warnings,
      errors: [`Expected 13-16 positions, got ${parts.length}. Too many hyphen-separated segments.`],
    };
  }

  // Detect v3.2 vs v3.3 by examining position index 12
  // v3.3: index 12 = country code (2-letter alpha in VALID_COUNTRY_CODES)
  // v3.2: index 12 = creation date (8-digit YYYYMMDD)
  const positionAt12 = parts[12];
  let formatVersion: "v3.3" | "v3.2";

  if (VALID_COUNTRY_CODES.has(positionAt12)) {
    formatVersion = "v3.3";
  } else if (CREATION_DATE_PATTERN.test(positionAt12)) {
    formatVersion = "v3.2";
  } else if (/^[a-z]{2}$/.test(positionAt12)) {
    // 2-letter alpha but not in known country codes — treat as v3.3 (future-proof)
    formatVersion = "v3.3";
    warnings.push(`Unknown country code "${positionAt12}" at position 13 — treating as v3.3 format`);
  } else {
    return {
      status: "ERROR",
      warnings,
      errors: [`Cannot determine format version: position 13 "${positionAt12}" is neither a country code nor a date`],
    };
  }

  let positions: AssetIdPositions;

  if (formatVersion === "v3.3") {
    // v3.3: 14 positions (no promo) or 15 positions (with promo)
    if (parts.length < 14 || parts.length > 15) {
      return {
        status: "ERROR",
        warnings,
        errors: [`v3.3 format expects 14-15 positions, got ${parts.length}`],
      };
    }

    positions = {
      funnel: parts[0],
      script_id: parts[1],
      variation_id: parts[2],
      platform: parts[3],
      dimensions: parts[4],
      length_tier: parts[5],
      ad_category: parts[6],
      expansion_type: parts[7],
      asset_type: parts[8],
      talent_code: parts[9],
      editor_initials: parts[10],
      copywriter_initials: parts[11],
      country_code: parts[12],
      creation_date: parts[13],
      ...(parts[14] ? { promo_name: parts[14] } : {}),
    };
  } else {
    // v3.2: 13 positions (no promo) or 14 positions (with promo), no country code
    if (parts.length < 13 || parts.length > 14) {
      return {
        status: "ERROR",
        warnings,
        errors: [`v3.2 format expects 13-14 positions, got ${parts.length}`],
      };
    }

    warnings.push("v3.2 format detected (no country code) — defaulting to \"us\"");

    positions = {
      funnel: parts[0],
      script_id: parts[1],
      variation_id: parts[2],
      platform: parts[3],
      dimensions: parts[4],
      length_tier: parts[5],
      ad_category: parts[6],
      expansion_type: parts[7],
      asset_type: parts[8],
      talent_code: parts[9],
      editor_initials: parts[10],
      copywriter_initials: parts[11],
      country_code: "us",  // default for v3.2
      creation_date: parts[12],
      ...(parts[13] ? { promo_name: parts[13] } : {}),
    };
  }

  // Validate individual positions
  if (!SCRIPT_ID_PATTERN.test(positions.script_id)) {
    warnings.push(`ScriptID "${positions.script_id}" does not match expected pattern (4 digits, i+3, or h+3-4)`);
  }

  if (!VARIATION_ID_PATTERN.test(positions.variation_id)) {
    errors.push(`Invalid VariationID: "${positions.variation_id}"`);
  }

  if (!VALID_PLATFORMS.has(positions.platform)) {
    errors.push(`Invalid Platform: "${positions.platform}"`);
  }

  if (!DIMENSIONS_PATTERN.test(positions.dimensions)) {
    errors.push(`Invalid Dimensions: "${positions.dimensions}"`);
  }

  if (!VALID_LENGTH_TIERS.has(positions.length_tier)) {
    errors.push(`Invalid LengthTier: "${positions.length_tier}"`);
  }

  if (!PARSER_AD_CATEGORIES.has(positions.ad_category)) {
    errors.push(`Invalid AdCategory: "${positions.ad_category}"`);
  } else if (positions.ad_category === "ver" || positions.ad_category === "hor") {
    warnings.push(`Legacy AdCategory "${positions.ad_category}" — use exv/exh for new assets`);
  }

  if (!VALID_EXPANSION_TYPES.has(positions.expansion_type)) {
    errors.push(`Invalid ExpansionType: "${positions.expansion_type}"`);
  }

  if (!VALID_ASSET_TYPES.has(positions.asset_type)) {
    errors.push(`Invalid AssetType: "${positions.asset_type}"`);
  }

  if (positions.talent_code.length !== 4) {
    warnings.push(`TalentCode "${positions.talent_code}" is not 4 characters`);
  }

  if (!CREATION_DATE_PATTERN.test(positions.creation_date)) {
    errors.push(`Invalid CreationDate: "${positions.creation_date}"`);
  }

  return {
    status: errors.length > 0 ? "ERROR" : "PARSED",
    positions,
    format_version: formatVersion,
    warnings,
    errors,
  };
}

/**
 * Best-effort parser for old-format Asset IDs (< 13 positions).
 *
 * Production assets from before the v3.2/v3.3 naming convention have fewer
 * positions and different ordering. We extract what we can:
 * - Positions 0-2 (funnel, script_id, variation_id) are always reliable
 * - Remaining positions are matched heuristically by pattern
 * - Unmatched fields get placeholder defaults — callers should use RawIntake
 *   overrides to supply correct values
 */
function parseOldFormat(parts: string[], warnings: string[]): ParseResult {
  warnings.push(`Old-format asset ID (${parts.length} positions) — using heuristic parsing. Some inherited fields may be incorrect.`);

  // Positions 0-2 are always funnel, script_id, variation_id
  const funnel = parts[0];
  const scriptId = parts[1];
  const variationId = parts[2];

  // Scan remaining positions (3+) for recognizable patterns
  const remaining = parts.slice(3);

  let dimensions = "9x16";      // default
  let platform = "fb";          // default
  let lengthTier = "60s";       // default (mapped from old "1min")
  let adCategory = "nn";        // default
  let assetType = "vd";         // default (legacy generic video)
  let talentCode = "unkn";      // default
  let editorInitials = "xx";    // default
  let copywriterInitials = "xx"; // default
  let countryCode = "us";       // default
  let creationDate = "20260101"; // default
  let promoName: string | undefined;

  for (const part of remaining) {
    if (DIMENSIONS_PATTERN.test(part)) {
      dimensions = part;
    } else if (VALID_PLATFORMS.has(part)) {
      platform = part;
    } else if (VALID_LENGTH_TIERS.has(part)) {
      lengthTier = part;
    } else if (OLD_LENGTH_TIER_MAP[part]) {
      lengthTier = OLD_LENGTH_TIER_MAP[part];
    } else if (VALID_AD_CATEGORIES.has(part) || part === "ver" || part === "hor") {
      adCategory = part;
    } else if (PARSER_ASSET_TYPES.has(part)) {
      assetType = part;
    } else if (VALID_COUNTRY_CODES.has(part)) {
      countryCode = part;
    } else if (CREATION_DATE_PATTERN.test(part)) {
      creationDate = part;
    } else if (part.length === 4 && /^[a-z]{4}$/.test(part)) {
      // 4-letter lowercase — likely talent code
      if (talentCode === "unkn") {
        talentCode = part;
      } else if (editorInitials === "xx") {
        editorInitials = part;
      }
    } else if (part.length >= 2 && part.length <= 4 && /^[a-z]+$/.test(part)) {
      // 2-4 letter code — could be editor/copywriter initials
      if (editorInitials === "xx") {
        editorInitials = part;
      } else if (copywriterInitials === "xx") {
        copywriterInitials = part;
      }
    } else {
      // Anything else is treated as promo name (or ignored)
      if (!promoName) {
        promoName = part;
      }
    }
  }

  // Validate variation_id
  const errors: string[] = [];
  if (!VARIATION_ID_PATTERN.test(variationId)) {
    errors.push(`Invalid VariationID: "${variationId}"`);
  }
  if (!SCRIPT_ID_PATTERN.test(scriptId)) {
    warnings.push(`ScriptID "${scriptId}" does not match expected pattern`);
  }

  const positions: AssetIdPositions = {
    funnel,
    script_id: scriptId,
    variation_id: variationId,
    platform,
    dimensions,
    length_tier: lengthTier,
    ad_category: adCategory,
    expansion_type: "xx",  // old-format assets are originals (net new)
    asset_type: assetType,
    talent_code: talentCode,
    editor_initials: editorInitials,
    copywriter_initials: copywriterInitials,
    country_code: countryCode,
    creation_date: creationDate,
    ...(promoName ? { promo_name: promoName } : {}),
  };

  return {
    status: errors.length > 0 ? "ERROR" : "PARSED",
    positions,
    format_version: "v3.2", // closest match
    warnings,
    errors,
  };
}
