// Code generated by MockGen. DO NOT EDIT.
// Source: osv/client/osvclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOsvClient is a mock of OsvClient interface.
type MockOsvClient struct {
	ctrl     *gomock.Controller
	recorder *MockOsvClientMockRecorder
}

// MockOsvClientMockRecorder is the mock recorder for MockOsvClient.
type MockOsvClientMockRecorder struct {
	mock *MockOsvClient
}

// NewMockOsvClient creates a new mock instance.
func NewMockOsvClient(ctrl *gomock.Controller) *MockOsvClient {
	mock := &MockOsvClient{ctrl: ctrl}
	mock.recorder = &MockOsvClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOsvClient) EXPECT() *MockOsvClientMockRecorder {
	return m.recorder
}

// ScanSecrets mocks base method.
func (m *MockOsvClient) ScanSecrets(ctx context.Context, root string, ignoreDirectories []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanSecrets", ctx, root, ignoreDirectories)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanSecrets indicates an expected call of ScanSecrets.
func (mr *MockOsvClientMockRecorder) ScanSecrets(ctx, root, ignoreDirectories interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanSecrets", reflect.TypeOf((*MockOsvClient)(nil).ScanSecrets), ctx, root, ignoreDirectories)
}
