// Code generated by MockGen. DO NOT EDIT.
// Source: rag/client/ragclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRagClient is a mock of RagClient interface.
type MockRagClient struct {
	ctrl     *gomock.Controller
	recorder *MockRagClientMockRecorder
}

// MockRagClientMockRecorder is the mock recorder for MockRagClient.
type MockRagClientMockRecorder struct {
	mock *MockRagClient
}

// NewMockRagClient creates a new mock instance.
func NewMockRagClient(ctrl *gomock.Controller) *MockRagClient {
	mock := &MockRagClient{ctrl: ctrl}
	mock.recorder = &MockRagClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRagClient) EXPECT() *MockRagClientMockRecorder {
	return m.recorder
}

// QueryPatterns mocks base method.
func (m *MockRagClient) QueryPatterns(ctx context.Context, query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryPatterns", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryPatterns indicates an expected call of QueryPatterns.
func (mr *MockRagClientMockRecorder) QueryPatterns(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryPatterns", reflect.TypeOf((*MockRagClient)(nil).QueryPatterns), ctx, query)
}

// Queryknowledge mocks base method.
func (m *MockRagClient) Queryknowledge(ctx context.Context, query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Queryknowledge", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Queryknowledge indicates an expected call of Queryknowledge.
func (mr *MockRagClientMockRecorder) Queryknowledge(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queryknowledge", reflect.TypeOf((*MockRagClient)(nil).Queryknowledge), ctx, query)
}
