// Code generated by MockGen. DO NOT EDIT.
// Source: iam/client/iamclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iamclient "devops-mcp-server/iam/client"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cloudresourcemanager "google.golang.org/api/cloudresourcemanager/v1"
	iam "google.golang.org/api/iam/v1"
)

// MockIAMClient is a mock of IAMClient interface.
type MockIAMClient struct {
	ctrl     *gomock.Controller
	recorder *MockIAMClientMockRecorder
}

// MockIAMClientMockRecorder is the mock recorder for MockIAMClient.
type MockIAMClientMockRecorder struct {
	mock *MockIAMClient
}

// NewMockIAMClient creates a new mock instance.
func NewMockIAMClient(ctrl *gomock.Controller) *MockIAMClient {
	mock := &MockIAMClient{ctrl: ctrl}
	mock.recorder = &MockIAMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAMClient) EXPECT() *MockIAMClientMockRecorder {
	return m.recorder
}

// AddIAMRoleBinding mocks base method.
func (m *MockIAMClient) AddIAMRoleBinding(ctx context.Context, resourceID, role, member string) (*cloudresourcemanager.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIAMRoleBinding", ctx, resourceID, role, member)
	ret0, _ := ret[0].(*cloudresourcemanager.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddIAMRoleBinding indicates an expected call of AddIAMRoleBinding.
func (mr *MockIAMClientMockRecorder) AddIAMRoleBinding(ctx, resourceID, role, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIAMRoleBinding", reflect.TypeOf((*MockIAMClient)(nil).AddIAMRoleBinding), ctx, resourceID, role, member)
}

// CreateServiceAccount mocks base method.
func (m *MockIAMClient) CreateServiceAccount(ctx context.Context, projectID, displayName, accountID string) (*iam.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceAccount", ctx, projectID, displayName, accountID)
	ret0, _ := ret[0].(*iam.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceAccount indicates an expected call of CreateServiceAccount.
func (mr *MockIAMClientMockRecorder) CreateServiceAccount(ctx, projectID, displayName, accountID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccount", reflect.TypeOf((*MockIAMClient)(nil).CreateServiceAccount), ctx, projectID, displayName, accountID)
}

// GetIAMRoleBinding mocks base method.
func (m *MockIAMClient) GetIAMRoleBinding(ctx context.Context, projectID, serviceAccountEmail string) (*iamclient.RoleBindingList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIAMRoleBinding", ctx, projectID, serviceAccountEmail)
	ret0, _ := ret[0].(*iamclient.RoleBindingList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIAMRoleBinding indicates an expected call of GetIAMRoleBinding.
func (mr *MockIAMClientMockRecorder) GetIAMRoleBinding(ctx, projectID, serviceAccountEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIAMRoleBinding", reflect.TypeOf((*MockIAMClient)(nil).GetIAMRoleBinding), ctx, projectID, serviceAccountEmail)
}

// ListServiceAccounts mocks base method.
func (m *MockIAMClient) ListServiceAccounts(ctx context.Context, projectID string) (*iamclient.ServiceAccountList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServiceAccounts", ctx, projectID)
	ret0, _ := ret[0].(*iamclient.ServiceAccountList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceAccounts indicates an expected call of ListServiceAccounts.
func (mr *MockIAMClientMockRecorder) ListServiceAccounts(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceAccounts", reflect.TypeOf((*MockIAMClient)(nil).ListServiceAccounts), ctx, projectID)
}
