// Code generated by MockGen. DO NOT EDIT.
// Source: resourcemanager/client/resourcemanagerclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResourcemanagerClient is a mock of ResourcemanagerClient interface.
type MockResourcemanagerClient struct {
	ctrl     *gomock.Controller
	recorder *MockResourcemanagerClientMockRecorder
}

// MockResourcemanagerClientMockRecorder is the mock recorder for MockResourcemanagerClient.
type MockResourcemanagerClientMockRecorder struct {
	mock *MockResourcemanagerClient
}

// NewMockResourcemanagerClient creates a new mock instance.
func NewMockResourcemanagerClient(ctrl *gomock.Controller) *MockResourcemanagerClient {
	mock := &MockResourcemanagerClient{ctrl: ctrl}
	mock.recorder = &MockResourcemanagerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourcemanagerClient) EXPECT() *MockResourcemanagerClientMockRecorder {
	return m.recorder
}

// ToProjectNumber mocks base method.
func (m *MockResourcemanagerClient) ToProjectNumber(ctx context.Context, projectID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToProjectNumber", ctx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToProjectNumber indicates an expected call of ToProjectNumber.
func (mr *MockResourcemanagerClientMockRecorder) ToProjectNumber(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToProjectNumber", reflect.TypeOf((*MockResourcemanagerClient)(nil).ToProjectNumber), ctx, projectID)
}
