// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBM25Client is a mock of BM25Client interface.
type MockBM25Client struct {
	ctrl     *gomock.Controller
	recorder *MockBM25ClientMockRecorder
}

// MockBM25ClientMockRecorder is the mock recorder for MockBM25Client.
type MockBM25ClientMockRecorder struct {
	mock *MockBM25Client
}

// NewMockBM25Client creates a new mock instance.
func NewMockBM25Client(ctrl *gomock.Controller) *MockBM25Client {
	mock := &MockBM25Client{ctrl: ctrl}
	mock.recorder = &MockBM25ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBM25Client) EXPECT() *MockBM25ClientMockRecorder {
	return m.recorder
}

// QueryPatterns mocks base method.
func (m *MockBM25Client) QueryPatterns(ctx context.Context, query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryPatterns", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryPatterns indicates an expected call of QueryPatterns.
func (mr *MockBM25ClientMockRecorder) QueryPatterns(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryPatterns", reflect.TypeOf((*MockBM25Client)(nil).QueryPatterns), ctx, query)
}

// Queryknowledge mocks base method.
func (m *MockBM25Client) Queryknowledge(ctx context.Context, query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Queryknowledge", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Queryknowledge indicates an expected call of Queryknowledge.
func (mr *MockBM25ClientMockRecorder) Queryknowledge(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queryknowledge", reflect.TypeOf((*MockBM25Client)(nil).Queryknowledge), ctx, query)
}
